apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
stringData:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword }}
  password: {{ .Values.postgresql.auth.password }}
