apiVersion: v1
kind: Service
metadata:
  name: sleep-track-service
  labels:
    app: sleep-track
spec:
  selector:
    app: sleep-track
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
