apiVersion: v2
name: sleep-track
description: Sleep tracker API
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 16.7.16
    repository: oci://registry-1.docker.io/bitnamicharts
