apiVersion: v2
name: sleep-track
description: Sleep tracker API
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    version: 16.7.16
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: swaggerui
    version: 0.3.7
    repository: https://chrisfu.github.io/charts
