postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: ""
    username: sleeptrack
    database: sleeptrack
    password: ""
    existingSecret: postgres-secret
    secretKeys:
      userPasswordKey: password

swaggerui:
  image:
    tag: v5.26.2
  swaggerui:
    jsonUrl: /openapi.json
  deployment:
    extraEnv:
      - name: BASE_URL
        value: /docs
