postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: ""
    username: sleeptrack
    database: sleeptrack
    password: ""
    existingSecret: postgres-secret
    secretKeys:
      userPasswordKey: password
